### PR TITLE
Rename tasks to be closer to Ansible convention

### PR DESCRIPTION
**Pull request by l00ptr**
We try to fix some (small) issues with tasks names and adapt them to respect (as much as possible) the recommended convention from ansible-lint and Ansible:

https://ansible.readthedocs.io/projects/lint/rules/name/

Basicly we:

- Remove the useless "
- Ensure all tasks names start with a Capital letter
- Add a prefix for tasks within sub-tasks files
- Avoid templating in tasks names
- Try to use / favorise present-tense and imperative style

### CODE REVIEW

**Comment by staticdev** [comment]
If @aalaesar agrees, I am all in.

**Review by aalaesar — APPROVED** [review]
LGTM
Thank you @l00ptr for taking the time to improve the role 👍 
And thx  @staticdev  for the reminder 😄

**Comment by l00ptr** [comment]
@aalaesar so what about the failing CI ? Can we / you merge that PR ?

**Comment by staticdev** [comment]
> @aalaesar so what about the failing CI ? Can we / you merge that PR ?

I am trying to rerun.. we are fighting some flakeness on GA for some time in this repo, but all works good xD

**Comment by staticdev** [comment]
I see the errors we have are not related to the PR, and i created a new issue. No reason to wait longer. Thanks @l00ptr !

**Pull request merged**
