### PR TITLE
Cleanup unnecessary block statement in nc-apps.ymls.

### PR DESCRIPTION
**Pull request by marioqxx**
This is a simple cleanup. It removes an unnecessary block-statement that has remained. The mainy changes it suggests to include are only removal of leading spaces for correct indentation.

### CODE REVIEW

**Review by wiktor2200 — DISMISSED** [review]
LGTM

**Comment by staticdev** [comment]
@marioqxx yto merge we need you to do a `git commit --amend` and add your email to commit message to pass the DCO.

**Review by staticdev — CHANGES_REQUESTED** [review]
Need to pass DCO.

**Comment by marioqxx** [comment]
> @marioqxx yto merge we need you to do a `git commit --amend` and add your email to commit message to pass the DCO. After that you can `git push -f`.

@staticdev: Thanks again for help. I needed to use commit -s --amend.

**Review by wiktor2200 — APPROVED** [review]

**Review by staticdev — APPROVED** [review]

**Pull request merged**
