### PR TITLE
WIP: Feature/add backup role

### PR DESCRIPTION
**Pull request by staticdev**
Adds backup role as discussed in https://github.com/nextcloud/ansible-collection-nextcloud-admin/discussions/228

### CODE REVIEW

**Comment by aalaesar** [comment]
Hello there!

I remember the discussion in #228  about the backup role.
Thank you @staticdev  for the initiative. As discusted, this will need probably more refinement before GA
also, on a pure Git perspective, it would be great to keep the commit history for the role.

Regards.

**Comment by aalaesar** [comment]
We may need to revert update to the CI with dependabot as latest broke our CI :
https://github.com/nextcloud/ansible-collection-nextcloud-admin/actions/runs/4767463169/jobs/8475717509?pr=260#step:7:68
or fix it for main

**Comment by staticdev** [comment]
> We may need to revert update to the CI with dependabot as latest broke our CI : https://github.com/nextcloud/ansible-collection-nextcloud-admin/actions/runs/4767463169/jobs/8475717509?pr=260#step:7:68 or fix it for main

About the errors we get, they are related to molecule 5. I created a new PR https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/261 improving test running that also fixes the error (I tested before on some other roles).

**Comment by staticdev** [comment]
> Hello there!
> 
> I remember the discussion in #228 about the backup role. Thank you @staticdev for the initiative. As discusted, this will need probably more refinement before GA also, on a pure Git perspective, it would be great to keep the commit history for the role.
> 
> Regards.

I feel we can add the role and do the improvements here as we go. As for the commit history, you can archive the other repo as history for investigation and we can point to a link in the docs so it is available in case of need. What do you think?

**Comment by wiktor2200** [comment]
Hi! As this collection become official Nextcloud role I would opt for releasing backup into it when fully finished and tested. So now we could go one of 2 ways - first way: develop on @aalaesar's repo and then on some level move it or second way: move it here, but not to main branch, but to some "dev", "nc-backup-rc" or similar. Then test it here and release to GA when ready. 
That's just my suggestions. 
I've started using this role some time ago and backup works like charm :) I've tested only partial manual restore, so it also need to be covered in some way before release.

Btw, it's possible to "merge" one repo into another without loosing any history and commits, I've done it once in the past. I could try again tomorrow if we decide which approach we want to take :)

**Comment by aalaesar** [comment]
Hello there !
I'm very busy at the moment so I can't response quickly  to you. I thank you for keeping the repo active.

> Then test it here and release to GA when ready. That's just my suggestions. I've started using this role some time ago and backup works like charm :)

Ok. What would be the list of features making the backup role worthy  of being released ?

> I've tested only partial manual restore, so it also need to be covered in some way before release.
Yep potentially adding an install from backup option in Install nextcloud ? Or a new role ? Or inside the backup roles ?

> Btw, it's possible to "merge" one repo into another without loosing any history and commits, I've done it once in the past. I could try again tomorrow if we decide which approach we want to take :)

Yes I would  prefer this approach.  😃 

Regard.

**Comment by wiktor2200** [comment]
Hi @aalaesar!

> Ok. What would be the list of features making the backup role worthy of being released ?

For my opinion some testing and documentation or maybe even test task in Molecule would be sufficient for now. I'm also quite busy right now, so when I will find some time I will definitely add my two cents and contribute.

> Yep potentially adding an install from backup option in Install nextcloud ? Or a new role ? Or inside the backup roles ?

I would opt for adding backup role next to nextcloud_install as separate role in collection. It would be probably easier to maintain and will give more flexibility.

> Yes I would prefer this approach.

Ok, so I will try to make PR for that when have some time ;)

**Comment by wiktor2200** [comment]
Hi @aalaesar @staticdev!
I've added whole role with commit history from: https://github.com/aalaesar/backup_nextcloud in #268
@staticdev please take a look if you can push your commits to this PR, so whole feature will be available to merge, when we decide it's ready ;)

**Comment by staticdev** [comment]
> 

Probably will be able to do throughout the week or latest next weekend.

**Comment by staticdev** [comment]
Done @wiktor2200 @aalaesar, closing this one in favor to #268

**Pull request closed without merging**
