### PR TITLE
Add nextcloud backup role

### PR DESCRIPTION
**Pull request by wiktor2200**
Hi @aalaesar @staticdev!
As mentioned in #260 I'm adding role to this repo as copy of @aalaesar role with whole commit hisotry.
It's adding backup role as discussed in #228.

### CODE REVIEW

**Comment by wiktor2200** [comment]
FYI: @aalaesar @staticdev
I also updated license to be the same as for whole collection GPL3 -> BSD.

**Comment by staticdev** [comment]
@wiktor2200 I do not have permissions to push to your fork.. should I fork your fork and create a PR there XD?

**Comment by wiktor2200** [comment]
Hi! @staticdev @aalaesar I've invited you as collaborators to my fork, so now you would be able to commit to my branch and this PR would be updated automatically. :)

**Review by staticdev — APPROVED** [review]
@aalaesar @wiktor2200 From my side, I think we should merge. Now we have the history, I was able to do some smoke test and also informed in the main readme of the collection that this role is in beta. Also the code is not entirely new, and we can handle next steps in enhancement and bugfix issues. What do you think? LGTM?

**Comment by wiktor2200** [comment]
Hi @staticdev! Sorry for late response, been busy recently. I think we are ready to merge, old code is imported, new changes are added and we've got commit history.
And as it's marked as `beta` everyone probably take that into consideration before use, nevertheless it works. 
As next steps we can create some molecule tests to create whole deploy -> backup -> restore process.
@aalaesar, do you agree? :)

**Pull request merged**
