### PR TITLE
Change role description

### PR DESCRIPTION
**Pull request by wiktor2200**
I would propose description change for Ansible Collection. In my opinion having it mentioned that it's Official under Nextcloud organization may be beneficial.

### CODE REVIEW

**Review by aalaesar — APPROVED** [review]
LGTM

**Comment by staticdev** [comment]
You are toont fast for me these days sorry. Super busy here and also struggling with losing files from my nextcloud instalation (trying to understand why)

**Comment by wiktor2200** [comment]
Hi @staticdev! No problem at all, @aalaesar has already approved :)

Oh.. your problem sounds serious. I had similar problem in the past (for NC 20 AFAIR) and the problem was connected with one desktop client's old version. It had some problems with syncing, so when I added one file in one client, the other removed that.
But files were in "Deleted" folder, so I was able to restore. Start with checking your retention settings and client's logs (if you have such possibility).

**Comment by AndyScherzinger** [comment]
I am also a bit to late than... ;)

I would have suggested to drop the "Official " keyword, so people won't misinterpret it because Nextcloud (as a company) also offers support to paying customer. And the word "official" might suggest it is also part of what is supported under the payed subscription (spoiler: this isn't). Also currently no harm in having it in, I am aware you mean official in a different way - like under the Nextcloud umbrella/org.

**Comment by aalaesar** [comment]
Hello @AndyScherzinger ,
That's a fair point.
 Fortunately, the change has not been released yet so we can still find a not ambiguous  way to say that this is  a nextcloud  community  project

**Comment by wiktor2200** [comment]
Hi! Yes I meant `official in a different way - like under the Nextcloud umbrella/org`. So maybe to differentiate that it would be good to have: `Official community` to make sure that's still one of the ways, supported by community and not paid/enterprise solution. :thinking:

**Comment by wiktor2200** [comment]
Hi! Yes I meant `official in a different way - like under the Nextcloud umbrella/org`. So maybe to differentiate that it would be good to have: `Official community` to make sure that's still one of the ways, supported by community and not paid/enterprise solution.

**Pull request merged**
