### PR TITLE
Change namespace to nextcloud and collection name to admin

### PR DESCRIPTION
**Pull request by aalaesar**
requires:
- [x] #206 merged
- [x] #185 and #171 done
- [x] #216  merged
- [x] #186 done

changes : 
- changed all references of:
  - aalaesar.nextcloud => nextcloud.admin
  - aalaesar/install_nextcloud  => nextcloud/**ansible-collection-nextcloud-admin**  (expected repository new name)
- updated some titles

### CODE REVIEW

**Comment by wiktor2200** [comment]
Hi @aalaesar! 
As the collection PR is already merged, could you rebase this Draft? This will resolve conflicts and fast-forward to current main states, so this PR would be much smaller after all.

**Comment by staticdev** [comment]
@aalaesar basically the conflict files have:

```
  collections:
    - nextcloud.admin
```

But ansible-lint errors saying to remove it and use full-qualified name on roles instead such as:

```
  roles:
    - nextcloud.admin.install_nextcloud
```

**Comment by aalaesar** [comment]
> @aalaesar basically the conflict files have:
> 
> ```
>   collections:
>     - nextcloud.admin
> ```
> 
> But ansible-lint errors saying to remove it and use full-qualified name on roles instead such as:
> 
> ```
>   roles:
>     - nextcloud.admin.install_nextcloud
> ```

:+1:
Didn't got time to rebase yet 😃

**Comment by aalaesar** [comment]
LGTM
It's ready for reviewing :smiley:

**Review by staticdev — APPROVED** [review]

**Comment by staticdev** [comment]
LGTM =)

**Pull request merged**
